### ISSUE TITLE
Error in creating the 80x80x4 array

### ISSUE THREAD

**Issue by ritheshkumar95** [asrivat1/DeepLearningVideoGames#5]
This is one line in the code that you use to stack up 4 previous timesteps of the game state.

            s_t1 = np.append(x_t1, s_t[:,:,1:], axis = 2)

If you notice. If the s_t array at any point is [t1,t2,t3,t4] (let's say), the new s_t1 would be [t5,t2,t3,t4] and not [t2,t3,t4,t5].

Actually, the line should be, 

            s_t1 = np.append(s_t[:,:,1:],x_t1,axis=2)

**Comment by asrivat1** [comment]
This has been fixed in #13
